### PR TITLE
Fix before payment override

### PR DESCRIPTION
**Pull request by cpfergus1**
## Description
Removes decorator that overrides #before_payment and implements a decorator on Solidus::Stock::Differentiator which is the source of the problem

## Motivation and Context
An [issue on the support channel](https://solidusio.slack.com/archives/C0JBKDF35/p1655449617602479) made us realize that solidus_product_assembly is overriding the before_payment method on Spree::CheckoutsController. See https://github.com/solidusio-contrib/solidus_product_assembly/issues/110 for details. This is not ideal and we should aim to maintain functionality. This PR utilizes a different strategy to prevent assembly products from being removed from the order by modifying Solidus::Stock::Differentiator to ignore assembly products

## How Has This Been Tested?
The current test suite covers the changes made in the PR

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] ~~New feature (non-breaking change which adds functionality)~~
- [ ] ~~Breaking change (fix or feature that would cause existing functionality to not work as expected)~~

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by elia — APPROVED** [review]
Looks good to me, pending the lint failures

**Comment by gsmendoza** [comment]
Hi @cpfergus1 ! When I ran `bin/rake` locally with SOLIDUS_BRANCH set to v3.2, I got the following error:

```
Failures:

  1) Orders when the order product is not a bundle Splitting items allows admin to split items to another stock location
     Failure/Error: expect(page).to have_content /Pending package from '#{location_name}'/i
       expected to find text matching /Pending package from 'Foobar warehouse'/i in "Orders\nProducts\nPromotions\nStock\nUsers\nSettings\nMinimize Menu\nOrders\nR268783026\nShipments\nApprove Cancel Resend\nCart\nCustomer\nShipments\nAdjustments\nPayments\nRMA\nCustomer Returns\nCancel Items\nH13766636701 - Ready package from 'NY Warehouse'\nSend Shipment Email\nItem Description Price Quantity Total price\nProduct #79 - 6276\nSKU: SKU-129 $10.00 1 x on hand $10.00\nMove Product #79 - 6276 to\nFoobar warehouse (0 on hand)\nShipping Method UPS Ground $100.00\nTracking Number U10000\nOrder Total\n$110.00\nOrder Information\nStatus:\nComplete\nUser:\nemail19@example.com\nItem Total:\n$10.00\nShip Total:\n$100.00\nTotal:\n$110.00\nShipment:\nReady\nPayment:\nPaid\nCompleted at:\nOctober 13, 2022 10:14 AM\nFoobar warehouse (0 on hand)\nSave"
     # ./spec/features/admin/orders_spec.rb:123:in `block (4 levels) in <top (required)>'

```

I also got the error in CI when I ran the build with only Solidus 3.2. Please see https://app.circleci.com/pipelines/github/solidusio-contrib/solidus_product_assembly/261/workflows/fbd6e791-8f3f-4e3d-a324-e7d7c91ccbf4/jobs/605.

Can you confirm if you're also getting this spec failure?

**Comment by cpfergus1** [comment]
That spec was corrected with the addition of https://github.com/solidusio/solidus/pull/4625, but if it is not failing on master, something else must have changed 🤔

**Comment by gsmendoza** [comment]
@cpfergus1 I have updated the Circle CI orb to drop the test database at the end of each test-branch run (see https://github.com/solidusio/circleci-orbs-extensions/pull/58). However, it seems like this PR is not picking up that orb update. I think CircleCI might be caching the CI config for this PR. Can you try applying a non-edit amend to the last commit (`git commit --amend --no-edit`) and force push the branch? I'm hoping this would refresh the CI config for the PR. CC @elia

**Comment by cpfergus1** [comment]
> @cpfergus1 I have updated the Circle CI orb to drop the test database at the end of each test-branch run (see [solidusio/circleci-orbs-extensions#58](https://github.com/solidusio/circleci-orbs-extensions/pull/58)). However, it seems like this PR is not picking up that orb update. I think CircleCI might be caching the CI config for this PR. Can you try applying a non-edit amend to the last commit (`git commit --amend --no-edit`) and force push the branch? I'm hoping this would refresh the CI config for the PR. CC @elia

👍

**Pull request merged**
