### PR TITLE
Replace Deface Ruby with DSL

### PR DESCRIPTION
**Pull request by tmtrademarked**
This PR replaces the use of the Deface Ruby overrides with the Deface DSL. This makes this gem compatible with Rails 7.1, since the Deface overrides tend to break Zeitwerk naming conventions.

### CODE REVIEW

**Comment by tmtrademarked** [comment]
The spec failures here *appear* to not be related to my changes - but I'm not well enough versed in how these specs are set up to feel confident. Anyone have any suggestions on how to fix this?

**Comment by kennyadsl** [comment]
Thanks @tmtrademarked!

**Comment by kennyadsl** [comment]
We are on it @tmtrademarked, expect it today/tomorrow.

**Comment by tmtrademarked** [comment]
Wow, that's awesome - thanks a ton! Very much appreciated, as always. 🙏

**Comment by spaghetticode** [comment]
🎉 @tmtrademarked v1.4.0 has just been [released](https://rubygems.org/gems/solidus_product_assembly), thank you for your help!

**Pull request merged**
