### PR TITLE
add deface as a development dependency in gemspec

### PR DESCRIPTION
**Pull request by kevinjbayer**
Re: https://github.com/solidusio-contrib/solidus_product_assembly/issues/37

### CODE REVIEW

**Comment by kevinjbayer** [comment]
No problem. Just to be clear, I'm adding `require 'deface'` to /lib/solidus_product_assembly.rb and do you also want me to add `require: false` to the Gemfile?

**Comment by aitbw** [comment]
Yes, that is correct @kevinjbayer :ok_hand:

**Comment by kevinjbayer** [comment]
Sorry just saw your note about removing it from gemspec as well. Should be good now once checks complete.

**Comment by aitbw** [comment]
Don't worry and thanks! If you could squash your commits into one (with a short, descriptive message) would be great and that should be enough :relaxed:

**Comment by kevinjbayer** [comment]
So that was a first and a bit confusing, but I think I got it squashed properly. If not, let me know and I'll just start the whole damn thing over.

**Comment by kennyadsl** [comment]
Thanks!

**Pull request merged**
